service: sls-sds-crud

frameworkVersion: '1'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-northeast-1
  role: ${file(./config/role.yml)}

custom:
  environment:
    cluster_arn: ${file(./config/env.yml):cluster_arn}
    secret_arn: ${file(./config/env.yml):secret_arn}
    database_name: ${file(./config/env.yml):database_name}
    schema_name: ${file(./config/env.yml):schema_name}

package:
  exclude:
    - config/**
    - README.md

functions:
  get:
    handler: get.read
    events:
      - http:
          path: /
          method: get
    layers:
      - { Ref: CommonLambdaLayer }
    environment:
      CLUSTER_ARN: ${self:custom.environment.cluster_arn}
      SECRET_ARN: ${self:custom.environment.secret_arn}
      DATABASE_NAME: ${self:custom.environment.database_name}
      SCHEMA_NAME: ${self:custom.environment.schema_name}

  post:
    handler: post.create
    events:
      - http:
          path: /
          method: post
    layers:
      - { Ref: CommonLambdaLayer }
    environment:
      CLUSTER_ARN: ${self:custom.environment.cluster_arn}
      SECRET_ARN: ${self:custom.environment.secret_arn}
      DATABASE_NAME: ${self:custom.environment.database_name}
      SCHEMA_NAME: ${self:custom.environment.schema_name}

  delete:
    handler: delete.delete
    events:
      - http:
          path: /
          method: delete
    layers:
      - { Ref: CommonLambdaLayer }
    environment:
      CLUSTER_ARN: ${self:custom.environment.cluster_arn}
      SECRET_ARN: ${self:custom.environment.secret_arn}
      DATABASE_NAME: ${self:custom.environment.database_name}
      SCHEMA_NAME: ${self:custom.environment.schema_name}

  put:
    handler: put.update
    events:
      - http:
          path: /
          method: put
    layers:
      - { Ref: CommonLambdaLayer }
    environment:
      CLUSTER_ARN: ${self:custom.environment.cluster_arn}
      SECRET_ARN: ${self:custom.environment.secret_arn}
      DATABASE_NAME: ${self:custom.environment.database_name}
      SCHEMA_NAME: ${self:custom.environment.schema_name}

layers:
  common:
    path: layers
